name: "setup_cache"
description: "sets up the shared cache"
inputs:
  compiler:
    required: true
    type: string
  os:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Cache FetchContent dependencies
      uses: actions/cache@v4
      with:
        path: |
          build/_deps
        key: ${{ inputs.os }}-${{ inputs.compiler }}-deps-${{ hashFiles('cmake/FindEXT_TENSORSTORE.cmake', 'cmake/Findnlohmann_json_schema_validator.cmake') }}
        restore-keys: |
          ${{ inputs.os }}-${{ inputs.compiler }}-deps-
